if string.lower(RequiredScript) == "lib/tweak_data/dlctweakdata" then
	local data = DLCTweakData.init
	function DLCTweakData:init(tweak_data)
		data(self, tweak_data)
			self.starvr_free.content.loot_drops = {}
			self.pd2_clan.content.loot_drops = {}
			self.pd2_clan2.content.loot_drops = {}
			self.pd2_clan3.content.loot_drops = {}
			self.pd2_clan4.content.loot_drops = {}
			self.pd2_clan6.content.loot_drops = {}
			self.pd2_clan_crimefest_oct19.content.loot_drops = {}
			self.pd2_clan_johnwick.content.loot_drops = {}
			self.pd2_clan_crimefest_oct23.content.loot_drops = {}
			self.pd2_clan_lgl.content.loot_drops = {}
			self.crimefest2_u2.content.loot_drops = {}
			self.crimefest2_par.content.loot_drops = {}
			self.crimefest2_rave.content.loot_drops = {}
			self.crimefest2_u8.content.loot_drops = {}
			self.crimefest2_u9.content.loot_drops = {}
			self.pd2_clan_bonnie.content.loot_drops = {}
			self.poetry_soundtrack.content.loot_drops = {}
			self.gage_pack_shotgun.content.loot_drops = {}
			self.charliesierra.content.loot_drops = {}
			self.twitch_pack.content.loot_drops = {}
			self.twitch_pack2.content.loot_drops = {}
			self.humble_pack2.content.loot_drops = {}
			self.humble_pack3.content.loot_drops = {}
			self.humble_pack4.content.loot_drops = {}
			self.e3_s15a.content.loot_drops = {}
			self.e3_s15b.content.loot_drops = {}
			self.e3_s15c.content.loot_drops = {}
			self.e3_s15d.content.loot_drops = {}
			self.sweettooth.content.loot_drops = {}
			self.hlm_game.content.loot_drops = {}
			self.gage_pack_historical.content.loot_drops = {}
			self.alienware_alpha.content.loot_drops = {}
			self.goty_weapon_bundle_2014.content.loot_drops = {}
			self.goty_heist_bundle_2014.content.loot_drops = {}
			self.goty_dlc_bundle_2014.content.loot_drops = {}
			self.character_pack_clover.content.loot_drops = {}
			self.butch_pack_free.content.loot_drops = {
				{
					type_items = "weapon_mods",
					item_entry = "wpn_fps_upg_ns_ass_filter",
					amount = 1
				}
			}
			self.character_pack_dragan.content.loot_drops = {}
			self.overkill_pack.content.loot_drops = {}
			self.complete_overkill_pack.content.loot_drops = {}
			self.complete_overkill_pack2.content.loot_drops = {}
			self.complete_overkill_pack3.content.loot_drops = {}
			self.hlm2.content.loot_drops = {}
			self.hlm2_deluxe.content.loot_drops = {}
			self.speedrunners.content.loot_drops = {}
			self.bbq.content.loot_drops = {}
			self.west.content.loot_drops = {}
			self.arena.content.loot_drops = {}
			self.character_pack_sokol.content.loot_drops = {}
			self.turtles_mods_fix.content.loot_drops = {}
			self.dragon.content.loot_drops = {}
			self.dragon_maskfix.content.loot_drops = {}
			self.rip_free.content.loot_drops = {}
			self.tormentor_mask.content.loot_drops = {}
			self.coco.content.loot_drops = {}
			self.mad.content.loot_drops = {}
			self.pim.content.loot_drops = {}
			self.opera.content.loot_drops = {}
			self.jigg.content.loot_drops = {}
			self.dbd_clan_award.content.loot_drops = {}
			self.dbd_deluxe.content.loot_drops = {}
			self.pdcon_2015.content.loot_drops = {}
			self.pdcon_2016.content.loot_drops = {}
			self.bobblehead.content.loot_drops = {}
			self.free_jwshades.content.loot_drops = {}
			self.dbd_boo_0_award.content.loot_drops = {}
			self.dbd_boo_1_award.content.loot_drops = {}
			self.dbd_boo_4_award.content.loot_drops = {}
			self.wild.content.loot_drops = {}
			self.solus_clan_award.content.loot_drops = {}
			self.pd2_clan_migg.content.loot_drops = {}
			self.pd2_clan_fibb.content.loot_drops = {}
			self.gotti_bundle.content.loot_drops = {}
			self.nyck_bundle.content.loot_drops = {}
			self.urf_bundle.content.loot_drops = {}
			self.howl.content.loot_drops = {}
			self.tango.content.loot_drops = {}
			self.tango.content.loot_drops = {}
			self.win_bundle.content.loot_drops = {}
			self.chico_bundle.content.loot_drops = {}
			self.friend_bundle.content.loot_drops = {}
			self.swm_bundle.content.loot_drops = {}
			self.sparkle_bundle.content.loot_drops = {}
			self.sha_bundle.content.loot_drops = {}
			self.yor_bundle.content.loot_drops = {}
			self.bny_bundle.content.loot_drops = {}
			self.mp2_bundle.content.loot_drops = {}
			self.amp_bundle.content.loot_drops = {}
			self.flip_bundle.content.loot_drops = {}
			self.mdm_bundle.content.loot_drops = {}
			self.ant_free.content.loot_drops = {}
			self.ant.content.loot_drops = {}
			self.dgm_bundle.content.loot_drops = {}
			self.gcm_bundle.content.loot_drops = {}
			self.ztm_bundle.content.loot_drops = {}
			self.wmp_bundle.content.loot_drops = {}
			self.cmo_bundle.content.loot_drops = {}
			self.pbm_bundle.content.loot_drops = {}
			self.fdm_bundle.content.loot_drops = {}
			self.kwm_bundle.content.loot_drops = {}
			self.mmj_bundle.content.loot_drops = {}
			self.ecp_bundle.content.loot_drops = {}
			self.gwm_bundle.content.loot_drops = {}
			self.rvd_bundle.content.loot_drops = {}
			self.pmp_bundle.content.loot_drops = {}
			self.joy_bundle.content.loot_drops = {}
			self.ghm_bundle.content.loot_drops = {}
			self.khp_bundle.content.loot_drops = {}
			self.sdb_bundle.content.loot_drops = {}
			self.sms_bundle_1.content.loot_drops = {}
			self.sms_bundle_2.content.loot_drops = {}
			self.scm_bundle.content.loot_drops = {}
			self.ghx_bundle.content.loot_drops = {}
			self.sdm_bundle.content.loot_drops = {}
			self.flm_bundle.content.loot_drops = {}
			self.toon_bundle.content.loot_drops = {}
			self.mmh_bundle.content.loot_drops = {}
			self.maw_bundle.content.loot_drops = {}
			self.free_halloween_textures.content.loot_drops = {}
			self.gage_pack_shotgun_free.content.loot_drops = {}
			self.xmas_soundtrack.content.loot_drops = {}
			self.character_pack_sokol.content.loot_drops = {}
			self.dragon.content.loot_drops = {}
			self.steel_free.content.loot_drops = {}
			self.rip_free.content.loot_drops = {}
			self.tormentor_mask.content.loot_drops = {}
			self.halloween_nightmare_1.content.loot_drops = {}
			self.halloween_nightmare_2.content.loot_drops = {}
			self.halloween_nightmare_3.content.loot_drops = {}
			self.halloween_nightmare_4.content.loot_drops = {}
			
			self.gage_pack.content.loot_drops = {
				{
					type_items = "weapon_mods",
					item_entry = "wpn_fps_upg_i_singlefire",
					amount = 0
				},
				{
					type_items = "weapon_mods",
					item_entry = "wpn_fps_upg_i_autofire",
					amount = 0
				},
				{
					{
						type_items = "masks",
						item_entry = "goat",
						amount = 1
					},
					{
						type_items = "masks",
						item_entry = "panda",
						amount = 1
					},
					{
						type_items = "masks",
						item_entry = "pitbull",
						amount = 1
					},
					{
						type_items = "masks",
						item_entry = "eagle",
						amount = 1
					}
				},
				{
					{
						type_items = "materials",
						item_entry = "fur",
						amount = 1
					},
					{
						type_items = "materials",
						item_entry = "galvanized",
						amount = 1
					},
					{
						type_items = "materials",
						item_entry = "heavymetal",
						amount = 1
					},
					{
						type_items = "materials",
						item_entry = "oilmetal",
						amount = 1
					}
				},
				{
					{
						type_items = "textures",
						item_entry = "army",
						amount = 1
					},
					{
						type_items = "textures",
						item_entry = "commando",
						amount = 1
					},
					{
						type_items = "textures",
						item_entry = "hunter",
						amount = 1
					},
					{
						type_items = "textures",
						item_entry = "digitalcamo",
						amount = 1
					}
				}
			}
	end
end
if string.lower(RequiredScript) == "lib/tweak_data/gageassignmenttweakdata" then
	local data = GageAssignmentTweakData.init
	function GageAssignmentTweakData:init(tweak_data)
		data(self, tweak_data)
		self.assignments.green_mantis.aquire = 100
		self.assignments.yellow_bull.aquire = 100
		self.assignments.red_spider.aquire = 100
		self.assignments.blue_eagle.aquire = 100
		self.assignments.purple_snake.aquire = 100
	end
end
if string.lower(RequiredScript) == "lib/tweak_data/blackmarket/maskstweakdata" then
	local data = BlackMarketTweakData._init_masks
	function BlackMarketTweakData:_init_masks(tweak_data)
		data(self, tweak_data)
		
		self.masks.unicorn.pcs = {10, 20, 30, 40}
		self.masks.combusto.pcs = {10, 20, 30, 40}
		self.masks.spackle.pcs = {10, 20, 30, 40}
		self.masks.smiley.pcs = {10, 20, 30, 40}
		self.masks.gumbo.pcs = {10, 20, 30, 40}
		self.masks.crazy_lion.pcs = {10, 20, 30, 40}
		self.masks.mig_death.pcs = {10, 20, 30, 40}
		self.masks.mig_war.pcs = {10, 20, 30, 40}
		self.masks.mig_conquest.pcs = {10, 20, 30, 40}
		self.masks.mig_famine.pcs = {10, 20, 30, 40}
		self.masks.fib_fox.pcs = {10, 20, 30, 40}
		self.masks.fib_cat.pcs = {10, 20, 30, 40}
		self.masks.fib_mouse.pcs = {10, 20, 30, 40}
		self.masks.fib_hare.pcs = {10, 20, 30, 40}
		self.masks.wmp_01.pcs = {10, 20, 30, 40}
		self.masks.wmp_02.pcs = {10, 20, 30, 40}
		self.masks.wmp_03.pcs = {10, 20, 30, 40}
		self.masks.wmp_04.pcs = {10, 20, 30, 40}
		
		self.masks.simpson.pcs = {10, 20, 30, 40}
		self.masks.krampus.pcs = {10, 20, 30, 40}
		self.masks.mrs_claus.pcs = {10, 20, 30, 40}
		self.masks.strinch.pcs = {10, 20, 30, 40}
		self.masks.almirs_beard.pcs = {10, 20, 30, 40}
		self.masks.robo_santa.pcs = {10, 20, 30, 40}
		self.masks.champion_dallas.pcs = {10, 20, 30, 40}
		self.masks.baitface.pcs = {10, 20, 30, 40}
		self.masks.nomegusta.pcs = {10, 20, 30, 40}
		self.masks.rageface.pcs = {10, 20, 30, 40}
		self.masks.dawg.pcs = {10, 20, 30, 40}
		self.masks.rudeolph.pcs = {10, 20, 30, 40}
		self.masks.greedy_the_elf.pcs = {10, 20, 30, 40}
		self.masks.half_mask.pcs = {10, 20, 30, 40}
		self.masks.visor.pcs = {10, 20, 30, 40}
		self.masks.mad_goggles.pcs = {10, 20, 30, 40}
		self.masks.mad_mask.pcs = {10, 20, 30, 40}
		self.masks.nyck_beret.pcs = {10, 20, 30, 40}
		self.masks.nyck_pickle.pcs = {10, 20, 30, 40}
		self.masks.nyck_cap.pcs = {10, 20, 30, 40}
		self.masks.nyck_ace.pcs = {10, 20, 30, 40}
		self.masks.gti_al_capone.pcs = {10, 20, 30, 40}
		self.masks.gti_bugsy.pcs = {10, 20, 30, 40}
		self.masks.gti_madame_st_claire.pcs = {10, 20, 30, 40}
		self.masks.gti_lucky_luciano.pcs = {10, 20, 30, 40}
		self.masks.urf_seal.pcs = {10, 20, 30, 40}
		self.masks.moon_paycheck_dallas.pcs = {10, 20, 30, 40}
		self.masks.moon_paycheck_chains.pcs = {10, 20, 30, 40}
		self.masks.amp_01.pcs = {10, 20, 30, 40}
		self.masks.amp_02.pcs = {10, 20, 30, 40}
		self.masks.amp_03.pcs = {10, 20, 30, 40}
		self.masks.amp_04.pcs = {10, 20, 30, 40}
		self.masks.mp2_02.pcs = {10, 20, 30, 40}
		self.masks.mp2_03.pcs = {10, 20, 30, 40}
		self.masks.bny_01.pcs = {10, 20, 30, 40}
		self.masks.bny_02.pcs = {10, 20, 30, 40}
		self.masks.bny_03.pcs = {10, 20, 30, 40}
		self.masks.bny_04.pcs = {10, 20, 30, 40}
		self.masks.mmj.pcs = {10, 20, 30, 40}
		self.masks.cmo_01.pcs = {10, 20, 30, 40}
		self.masks.cmo_02.pcs = {10, 20, 30, 40}
		self.masks.cmo_03.pcs = {10, 20, 30, 40}
		self.masks.cmo_04.pcs = {10, 20, 30, 40}
		self.masks.kwm.pcs = {10, 20, 30, 40}
		self.masks.cmt_01.pcs = {10, 20, 30, 40}
		self.masks.cmt_02.pcs = {10, 20, 30, 40}
		self.masks.cmt_03.pcs = {10, 20, 30, 40}
		self.masks.cmt_04.pcs = {10, 20, 30, 40}
		self.masks.sdm_01.pcs = {10, 20, 30, 40}
		self.masks.sdm_02.pcs = {10, 20, 30, 40}
		self.masks.sdm_03.pcs = {10, 20, 30, 40}
		self.masks.sdm_04.pcs = {10, 20, 30, 40}
		self.masks.flm.pcs = {10, 20, 30, 40}
		self.masks.toon_01.pcs = {10, 20, 30, 40}
		self.masks.toon_02.pcs = {10, 20, 30, 40}
		self.masks.toon_03.pcs = {10, 20, 30, 40}
		self.masks.toon_04.pcs = {10, 20, 30, 40}
		
		self.masks.metalhead.pcs = {10, 20, 30, 40}
		self.masks.tcn.pcs = {10, 20, 30, 40}
		self.masks.surprise.pcs = {10, 20, 30, 40}
		self.masks.optimist_prime.pcs = {10, 20, 30, 40}
		self.masks.robberfly.pcs = {10, 20, 30, 40}
		self.masks.spider.pcs = {10, 20, 30, 40}
		self.masks.mantis.pcs = {10, 20, 30, 40}
		self.masks.wasp.pcs = {10, 20, 30, 40}
		self.masks.franklin.pcs = {10, 20, 30, 40}
		self.masks.lincoln.pcs = {10, 20, 30, 40}
		self.masks.grant.pcs = {10, 20, 30, 40}
		self.masks.washington.pcs = {10, 20, 30, 40}
		self.masks.silverback.pcs = {10, 20, 30, 40}
		self.masks.mandril.pcs = {10, 20, 30, 40}
		self.masks.skullmonkey.pcs = {10, 20, 30, 40}
		self.masks.orangutang.pcs = {10, 20, 30, 40}
		self.masks.galax.pcs = {10, 20, 30, 40}
		self.masks.crowgoblin.pcs = {10, 20, 30, 40}
		self.masks.evil.pcs = {10, 20, 30, 40}
		self.masks.volt.pcs = {10, 20, 30, 40}
		self.masks.white_wolf.pcs = {10, 20, 30, 40}
		self.masks.owl.pcs = {10, 20, 30, 40}
		self.masks.rabbit.pcs = {10, 20, 30, 40}
		self.masks.pig.pcs = {10, 20, 30, 40}
		self.masks.churchill.pcs = {10, 20, 30, 40}
		self.masks.red_hurricane.pcs = {10, 20, 30, 40}
		self.masks.patton.pcs = {10, 20, 30, 40}
		self.masks.de_gaulle.pcs = {10, 20, 30, 40}
		self.masks.msk_grizel.pcs = {10, 20, 30, 40}
		self.masks.medusa.pcs = {10, 20, 30, 40}
		self.masks.anubis.pcs = {10, 20, 30, 40}
		self.masks.pazuzu.pcs = {10, 20, 30, 40}
		self.masks.cursed_crown.pcs = {10, 20, 30, 40}
		self.masks.nun_town.pcs = {10, 20, 30, 40}
		self.masks.robo_arnold.pcs = {10, 20, 30, 40}
		self.masks.arch_nemesis.pcs = {10, 20, 30, 40}
		self.masks.dragan.pcs = {10, 20, 30, 40}
		self.masks.butcher.pcs = {10, 20, 30, 40}
		self.masks.doctor.pcs = {10, 20, 30, 40}
		self.masks.tech_lion.pcs = {10, 20, 30, 40}
		self.masks.lady_butcher.pcs = {10, 20, 30, 40}
		self.masks.carnotaurus.pcs = {10, 20, 30, 40}
		self.masks.triceratops.pcs = {10, 20, 30, 40}
		self.masks.pachy.pcs = {10, 20, 30, 40}
		self.masks.velociraptor.pcs = {10, 20, 30, 40}
		self.masks.the_overkill_mask.pcs = {10, 20, 30, 40}
		self.masks.firedemon.pcs = {10, 20, 30, 40}
		self.masks.gasmask.pcs = {10, 20, 30, 40}
		self.masks.firemask.pcs = {10, 20, 30, 40}
		self.masks.chef_hat.pcs = {10, 20, 30, 40}
		self.masks.bandit.pcs = {10, 20, 30, 40}
		self.masks.bullskull.pcs = {10, 20, 30, 40}
		self.masks.kangee.pcs = {10, 20, 30, 40}
		self.masks.lone.pcs = {10, 20, 30, 40}
		self.masks.concert_male.pcs = {10, 20, 30, 40}
		self.masks.concert_female.pcs = {10, 20, 30, 40}
		self.masks.boombox.pcs = {10, 20, 30, 40}
		self.masks.cantus.pcs = {10, 20, 30, 40}
		self.masks.sokol.pcs = {10, 20, 30, 40}
		self.masks.croupier_hat.pcs = {10, 20, 30, 40}
		self.masks.gladiator_helmet.pcs = {10, 20, 30, 40}
		self.masks.the_king_mask.pcs = {10, 20, 30, 40}
		self.masks.sports_utility_mask.pcs = {10, 20, 30, 40}
		self.masks.kage.pcs = {10, 20, 30, 40}
		self.masks.ninja_hood.pcs = {10, 20, 30, 40}
		self.masks.shirai.pcs = {10, 20, 30, 40}
		self.masks.slicer.pcs = {10, 20, 30, 40}
		self.masks.jiro.pcs = {10, 20, 30, 40}
		self.masks.mason_knight_veteran.pcs = {10, 20, 30, 40}
		self.masks.agatha_knight.pcs = {10, 20, 30, 40}
		self.masks.agatha_vanguard_veteran.pcs = {10, 20, 30, 40}
		self.masks.mason_vanguard_veteran.pcs = {10, 20, 30, 40}
		self.masks.water_spirit.pcs = {10, 20, 30, 40}
		self.masks.tane.pcs = {10, 20, 30, 40}
		self.masks.oro.pcs = {10, 20, 30, 40}
		self.masks.maui.pcs = {10, 20, 30, 40}
		self.masks.tall_goat.pcs = {10, 20, 30, 40}
		self.masks.goat_goat.pcs = {10, 20, 30, 40}
		self.masks.wet_goat.pcs = {10, 20, 30, 40}
		self.masks.fancy_goat.pcs = {10, 20, 30, 40}
		self.masks.horned_king.pcs = {10, 20, 30, 40}
		self.masks.viking.pcs = {10, 20, 30, 40}
		self.masks.nutcracker.pcs = {10, 20, 30, 40}
		self.masks.divided.pcs = {10, 20, 30, 40}
		self.masks.sydney.pcs = {10, 20, 30, 40}
		self.masks.born_biker_01.pcs = {10, 20, 30, 40}
		self.masks.born_biker_02.pcs = {10, 20, 30, 40}
		self.masks.born_biker_03.pcs = {10, 20, 30, 40}
		self.masks.brutal.pcs = {10, 20, 30, 40}
		self.masks.rust.pcs = {10, 20, 30, 40}
		self.masks.pim_dog.pcs = {10, 20, 30, 40}
		self.masks.pim_russian_ballistic.pcs = {10, 20, 30, 40}
		self.masks.pim_hotelier.pcs = {10, 20, 30, 40}
		self.masks.pim_mustang.pcs = {10, 20, 30, 40}
		self.masks.chc_terry.pcs = {10, 20, 30, 40}
		self.masks.chc_terry_begins.pcs = {10, 20, 30, 40}
		self.masks.sfm_01.pcs = {10, 20, 30, 40}
		self.masks.sfm_02.pcs = {10, 20, 30, 40}
		self.masks.sfm_03.pcs = {10, 20, 30, 40}
		self.masks.sfm_04.pcs = {10, 20, 30, 40}
		self.masks.spa_01.pcs = {10, 20, 30, 40}
		self.masks.spa_02.pcs = {10, 20, 30, 40}
		self.masks.spa_03.pcs = {10, 20, 30, 40}
		self.masks.spa_04.pcs = {10, 20, 30, 40}
		self.masks.grv_01.pcs = {10, 20, 30, 40}
		self.masks.grv_02.pcs = {10, 20, 30, 40}
		self.masks.grv_03.pcs = {10, 20, 30, 40}
		self.masks.grv_04.pcs = {10, 20, 30, 40}
		self.masks.ecp_male.pcs = {10, 20, 30, 40}
		self.masks.ecp_female.pcs = {10, 20, 30, 40}
		self.masks.ecp_male_begins.pcs = {10, 20, 30, 40}
		self.masks.ecp_female_begins.pcs = {10, 20, 30, 40}
		self.masks.bobblehead_dozer.pcs = {10, 20, 30, 40}
		
		self.masks.ancient.pcs = {10, 20, 30, 40}
		self.masks.twitch_orc.pcs = {10, 20, 30, 40}
		self.masks.the_one_below.pcs = {10, 20, 30, 40}
		self.masks.lycan.pcs = {10, 20, 30, 40}
		self.masks.area51.pcs = {10, 20, 30, 40}
		self.masks.alien_helmet.pcs = {10, 20, 30, 40}
		self.masks.titan.pcs = {10, 20, 30, 40}
		self.masks.pokachu.pcs = {10, 20, 30, 40}
		self.masks.moon.pcs = {10, 20, 30, 40}
		self.masks.borsuk.pcs = {10, 20, 30, 40}
		self.masks.card_jack.pcs = {10, 20, 30, 40}
		self.masks.card_queen.pcs = {10, 20, 30, 40}
		self.masks.card_king.pcs = {10, 20, 30, 40}
		self.masks.card_joker.pcs = {10, 20, 30, 40}
		self.masks.king_of_jesters.pcs = {10, 20, 30, 40}
		self.masks.hwl_dallas_zombie.pcs = {10, 20, 30, 40}
		self.masks.hwl_wolf_zombie.pcs = {10, 20, 30, 40}
		self.masks.hwl_hoxton_zombie.pcs = {10, 20, 30, 40}
		self.masks.howl_chains_zombie.pcs = {10, 20, 30, 40}
		self.masks.pdc16_clover.pcs = {10, 20, 30, 40}
		self.masks.spk_party.pcs = {10, 20, 30, 40}
		self.masks.fdm.pcs = {10, 20, 30, 40}
		self.masks.pbm.pcs = {10, 20, 30, 40}
		self.masks.swm_sydney.pcs = {10, 20, 30, 40}
		
		self.masks.panther.pcs = {10, 20, 30, 40}
		self.masks.rooster.pcs = {10, 20, 30, 40}
		self.masks.horse.pcs = {10, 20, 30, 40}
		self.masks.tiger.pcs = {10, 20, 30, 40}
		self.masks.jake.pcs = {10, 20, 30, 40}
		self.masks.richter.pcs = {10, 20, 30, 40}
		self.masks.biker.pcs = {10, 20, 30, 40}
		self.masks.alex.pcs = {10, 20, 30, 40}
		self.masks.corey.pcs = {10, 20, 30, 40}
		self.masks.tonys_revenge.pcs = {10, 20, 30, 40}
		self.masks.richard_returns.pcs = {10, 20, 30, 40}
		self.masks.hothead.pcs = {10, 20, 30, 40}
		self.masks.falcon.pcs = {10, 20, 30, 40}
		self.masks.unic.pcs = {10, 20, 30, 40}
		self.masks.speedrunner.pcs = {10, 20, 30, 40}
		self.masks.dbd_01.pcs = {10, 20, 30, 40}
		self.masks.dbd_02.pcs = {10, 20, 30, 40}
		self.masks.dbd_03.pcs = {10, 20, 30, 40}
		self.masks.dbd_04.pcs = {10, 20, 30, 40}
		self.masks.dbd_slasher.pcs = {10, 20, 30, 40}
		self.masks.ant_01.pcs = {10, 20, 30, 40}
		self.masks.ant_02.pcs = {10, 20, 30, 40}
		self.masks.ant_03.pcs = {10, 20, 30, 40}
		self.masks.ant_04.pcs = {10, 20, 30, 40}
		self.masks.ant_05.pcs = {10, 20, 30, 40}
		self.masks.ant_06.pcs = {10, 20, 30, 40}
		self.masks.ant_07.pcs = {10, 20, 30, 40}
		self.masks.ant_08.pcs = {10, 20, 30, 40}
		self.masks.eng_01.pcs = {10, 20, 30, 40}
		self.masks.eng_02.pcs = {10, 20, 30, 40}
		self.masks.eng_03.pcs = {10, 20, 30, 40}
		self.masks.eng_04.pcs = {10, 20, 30, 40}
		
		self.masks.bodhi.pcs = {10, 20, 30, 40}
		self.masks.bonnie.pcs = {10, 20, 30, 40}
		self.masks.grendel.pcs = {10, 20, 30, 40}
		self.masks.hectors_helmet.pcs = {10, 20, 30, 40}
		self.masks.jw_shades.pcs = {10, 20, 30, 40}
		self.masks.old_hoxton.pcs = {10, 20, 30, 40}
		self.masks.samurai.pcs = {10, 20, 30, 40}
		self.masks.starvr.pcs = {10, 20, 30, 40}
		self.masks.jimmy_duct.pcs = {10, 20, 30, 40}
		self.masks.dnm.pcs = {10, 20, 30, 40}
		self.masks.gitgud_e_wish.pcs = {10, 20, 30, 40}
		self.masks.gitgud_sm_wish.pcs = {10, 20, 30, 40}
		self.masks.ggac_od_t2.pcs = {10, 20, 30, 40}
		self.masks.mrm.pcs = {10, 20, 30, 40}
		self.masks.mmh.pcs = {10, 20, 30, 40}
		self.masks.joy.pcs = {10, 20, 30, 40}
		self.masks.ami_01.pcs = {10, 20, 30, 40}
		self.masks.ami_02.pcs = {10, 20, 30, 40}
		self.masks.ami_03.pcs = {10, 20, 30, 40}
		self.masks.ami_04.pcs = {10, 20, 30, 40}
		self.masks.ami_05.pcs = {10, 20, 30, 40}
		self.masks.ami_06.pcs = {10, 20, 30, 40}
		self.masks.tam.pcs = {10, 20, 30, 40}
		self.masks.maw_01.pcs = {10, 20, 30, 40}
		self.masks.dgm.pcs = {10, 20, 30, 40}
		self.masks.gcm.pcs = {10, 20, 30, 40}
		self.masks.gwm.pcs = {10, 20, 30, 40}
		self.masks.ghx.pcs = {10, 20, 30, 40}
		self.masks.ghm.pcs = {10, 20, 30, 40}
		self.masks.stoneface.pcs = {10, 20, 30, 40}
		self.masks.wayfarer.pcs = {10, 20, 30, 40}
		
		self.masks.fab_mega_grin.pcs = {10, 20, 30, 40}
		self.masks.fab_mega_doctor.pcs = {10, 20, 30, 40}
		self.masks.fab_mega_alien.pcs = {10, 20, 30, 40}
		self.masks.cop_mega_gage_blade.pcs = {10, 20, 30, 40}
		self.masks.fab_mega_mark.pcs = {10, 20, 30, 40}
		self.masks.dallas_glow.pcs = {10, 20, 30, 40}
		self.masks.wolf_glow.pcs = {10, 20, 30, 40}
		self.masks.hoxton_glow.pcs = {10, 20, 30, 40}
		self.masks.chains_glow.pcs = {10, 20, 30, 40}
		
		self.masks.unicorn.value = 3
		self.masks.combusto.value = 3
		self.masks.spackle.value = 3
		self.masks.smiley.value = 3
		self.masks.gumbo.value = 3
		self.masks.crazy_lion.value = 3
		self.masks.mig_death.value = 3
		self.masks.mig_war.value = 3
		self.masks.mig_conquest.value = 3
		self.masks.mig_famine.value = 3
		self.masks.fib_fox.value = 4
		self.masks.fib_cat.value = 4
		self.masks.fib_mouse.value = 4
		self.masks.fib_hare.value = 4
		self.masks.wmp_01.value = 3
		self.masks.wmp_02.value = 3
		self.masks.wmp_03.value = 3
		self.masks.wmp_04.value = 3
		
		self.masks.simpson.value = 4
		self.masks.krampus.value = 4
		self.masks.mrs_claus.value = 4
		self.masks.strinch.value = 4
		self.masks.almirs_beard.value = 4
		self.masks.robo_santa.value = 4
		self.masks.champion_dallas.value = 4
		self.masks.baitface.value = 4
		self.masks.nomegusta.value = 4
		self.masks.rageface.value = 4
		self.masks.dawg.value = 4
		self.masks.rudeolph.value = 4
		self.masks.greedy_the_elf.value = 4
		self.masks.half_mask.value = 4
		self.masks.visor.value = 4
		self.masks.mad_goggles.value = 4
		self.masks.mad_mask.value = 4
		self.masks.nyck_beret.value = 4
		self.masks.nyck_pickle.value = 4
		self.masks.nyck_cap.value = 4
		self.masks.nyck_ace.value = 4
		self.masks.gti_al_capone.value = 4
		self.masks.gti_bugsy.value = 4
		self.masks.gti_madame_st_claire.value = 4
		self.masks.gti_lucky_luciano.value = 4
		self.masks.urf_seal.value = 4
		self.masks.moon_paycheck_dallas.value = 4
		self.masks.moon_paycheck_chains.value = 4
		self.masks.amp_01.value = 4
		self.masks.amp_02.value = 4
		self.masks.amp_03.value = 4
		self.masks.amp_04.value = 4
		self.masks.mp2_02.value = 4
		self.masks.mp2_03.value = 4
		self.masks.bny_01.value = 4
		self.masks.bny_02.value = 4
		self.masks.bny_03.value = 4
		self.masks.bny_04.value = 4
		self.masks.mmj.value = 4
		self.masks.cmo_01.value = 4
		self.masks.cmo_02.value = 4
		self.masks.cmo_03.value = 4
		self.masks.cmo_04.value = 4
		self.masks.kwm.value = 4
		self.masks.cmt_01.value = 4
		self.masks.cmt_02.value = 4
		self.masks.cmt_03.value = 4
		self.masks.cmt_04.value = 4
		self.masks.sdm_01.value = 4
		self.masks.sdm_02.value = 4
		self.masks.sdm_03.value = 4
		self.masks.sdm_04.value = 4
		self.masks.flm.value = 4
		self.masks.toon_01.value = 5
		self.masks.toon_02.value = 5
		self.masks.toon_03.value = 5
		self.masks.toon_04.value = 5
		
		self.masks.metalhead.value = 5
		self.masks.tcn.value = 5
		self.masks.surprise.value = 5
		self.masks.optimist_prime.value = 5
		self.masks.robberfly.value = 5
		self.masks.spider.value = 5
		self.masks.mantis.value = 5
		self.masks.wasp.value = 5
		self.masks.franklin.value = 5
		self.masks.lincoln.value = 5
		self.masks.grant.value = 5
		self.masks.washington.value = 5
		self.masks.silverback.value = 5
		self.masks.mandril.value = 5
		self.masks.skullmonkey.value = 5
		self.masks.orangutang.value = 5
		self.masks.galax.value = 5
		self.masks.crowgoblin.value = 5
		self.masks.evil.value = 5
		self.masks.volt.value = 5
		self.masks.white_wolf.value = 5
		self.masks.owl.value = 5
		self.masks.rabbit.value = 5
		self.masks.pig.value = 5
		self.masks.churchill.value = 5
		self.masks.red_hurricane.value = 5
		self.masks.patton.value = 5
		self.masks.de_gaulle.value = 5
		self.masks.msk_grizel.value = 5
		self.masks.medusa.value = 5
		self.masks.anubis.value = 5
		self.masks.pazuzu.value = 5
		self.masks.cursed_crown.value = 5
		self.masks.nun_town.value = 5
		self.masks.robo_arnold.value = 5
		self.masks.arch_nemesis.value = 5
		self.masks.dragan.value = 5
		self.masks.butcher.value = 5
		self.masks.doctor.value = 5
		self.masks.tech_lion.value = 5
		self.masks.lady_butcher.value = 5
		self.masks.carnotaurus.value = 5
		self.masks.triceratops.value = 5
		self.masks.pachy.value = 5
		self.masks.velociraptor.value = 5
		self.masks.the_overkill_mask.value = 5
		self.masks.firedemon.value = 5
		self.masks.gasmask.value = 5
		self.masks.firemask.value = 5
		self.masks.chef_hat.value = 5
		self.masks.bandit.value = 5
		self.masks.bullskull.value = 5
		self.masks.kangee.value = 5
		self.masks.lone.value = 5
		self.masks.concert_male.value = 5
		self.masks.concert_female.value = 5
		self.masks.boombox.value = 5
		self.masks.cantus.value = 5
		self.masks.sokol.value = 5
		self.masks.croupier_hat.value = 5
		self.masks.gladiator_helmet.value = 5
		self.masks.the_king_mask.value = 5
		self.masks.sports_utility_mask.value = 5
		self.masks.kage.value = 5
		self.masks.ninja_hood.value = 5
		self.masks.shirai.value = 5
		self.masks.slicer.value = 5
		self.masks.jiro.value = 5
		self.masks.mason_knight_veteran.value = 5
		self.masks.agatha_knight.value = 5
		self.masks.agatha_vanguard_veteran.value = 5
		self.masks.mason_vanguard_veteran.value = 5
		self.masks.water_spirit.value = 5
		self.masks.tane.value = 5
		self.masks.oro.value = 5
		self.masks.maui.value = 5
		self.masks.tall_goat.value = 5
		self.masks.goat_goat.value = 5
		self.masks.wet_goat.value = 5
		self.masks.fancy_goat.value = 5
		self.masks.horned_king.value = 5
		self.masks.viking.value = 5
		self.masks.nutcracker.value = 5
		self.masks.divided.value = 5
		self.masks.sydney.value = 5
		self.masks.born_biker_01.value = 5
		self.masks.born_biker_02.value = 5
		self.masks.born_biker_03.value = 5
		self.masks.brutal.value = 5
		self.masks.rust.value = 5
		self.masks.pim_dog.value = 5
		self.masks.pim_russian_ballistic.value = 5
		self.masks.pim_hotelier.value = 5
		self.masks.pim_mustang.value = 5
		self.masks.chc_terry.value = 5
		self.masks.chc_terry_begins.value = 5
		self.masks.sfm_01.value = 5
		self.masks.sfm_02.value = 5
		self.masks.sfm_03.value = 5
		self.masks.sfm_04.value = 5
		self.masks.spa_01.value = 5
		self.masks.spa_02.value = 5
		self.masks.spa_03.value = 5
		self.masks.spa_04.value = 5
		self.masks.grv_01.value = 5
		self.masks.grv_02.value = 5
		self.masks.grv_03.value = 5
		self.masks.grv_04.value = 5
		self.masks.ecp_male.value = 5
		self.masks.ecp_female.value = 5
		self.masks.ecp_male_begins.value = 5
		self.masks.ecp_female_begins.value = 5
		self.masks.bobblehead_dozer.value = 5
		
		self.masks.ancient.value = 7
		self.masks.twitch_orc.value = 7
		self.masks.the_one_below.value = 7
		self.masks.lycan.value = 7
		self.masks.area51.value = 7
		self.masks.alien_helmet.value = 7
		self.masks.titan.value = 7
		self.masks.pokachu.value = 7
		self.masks.moon.value = 7
		self.masks.borsuk.value = 7
		self.masks.card_jack.value = 7
		self.masks.card_queen.value = 7
		self.masks.card_king.value = 7
		self.masks.card_joker.value = 7
		self.masks.king_of_jesters.value = 7
		self.masks.hwl_dallas_zombie.value = 7
		self.masks.hwl_wolf_zombie.value = 7
		self.masks.hwl_hoxton_zombie.value = 7
		self.masks.howl_chains_zombie.value = 7
		self.masks.pdc16_clover.value = 7
		self.masks.spk_party.value = 7
		self.masks.fdm.value = 7
		self.masks.pbm.value = 7
		self.masks.swm_sydney.value = 7
		
		self.masks.panther.value = 6
		self.masks.rooster.value = 6
		self.masks.horse.value = 6
		self.masks.tiger.value = 6
		self.masks.jake.value = 6
		self.masks.richter.value = 6
		self.masks.biker.value = 6
		self.masks.alex.value = 6
		self.masks.corey.value = 6
		self.masks.tonys_revenge.value = 6
		self.masks.richard_returns.value = 6
		self.masks.hothead.value = 6
		self.masks.falcon.value = 6
		self.masks.unic.value = 6
		self.masks.speedrunner.value = 6
		self.masks.dbd_01.value = 6
		self.masks.dbd_02.value = 6
		self.masks.dbd_03.value = 6
		self.masks.dbd_04.value = 6
		self.masks.dbd_slasher.value = 6
		self.masks.ant_01.value = 6
		self.masks.ant_02.value = 6
		self.masks.ant_03.value = 6
		self.masks.ant_04.value = 6
		self.masks.ant_05.value = 6
		self.masks.ant_06.value = 6
		self.masks.ant_07.value = 6
		self.masks.ant_08.value = 6
		self.masks.eng_01.value = 6
		self.masks.eng_02.value = 6
		self.masks.eng_03.value = 6
		self.masks.eng_04.value = 6
		
		self.masks.bodhi.value = 8
		self.masks.bonnie.value = 8
		self.masks.grendel.value = 8
		self.masks.hectors_helmet.value = 8
		self.masks.jw_shades.value = 8
		self.masks.old_hoxton.value = 8
		self.masks.samurai.value = 8
		self.masks.starvr.value = 8
		self.masks.jimmy_duct.value = 8
		self.masks.dnm.value = 8
		self.masks.gitgud_e_wish.value = 8
		self.masks.gitgud_sm_wish.value = 8
		self.masks.ggac_od_t2.value = 8
		self.masks.mrm.value = 8
		self.masks.mmh.value = 8
		self.masks.joy.value = 8
		self.masks.ami_01.value = 8
		self.masks.ami_02.value = 8
		self.masks.ami_03.value = 8
		self.masks.ami_04.value = 8
		self.masks.ami_05.value = 8
		self.masks.ami_06.value = 8
		self.masks.tam.value = 8
		self.masks.maw_01.value = 8
		self.masks.dgm.value = 8
		self.masks.gcm.value = 8
		self.masks.gwm.value = 8
		self.masks.ghx.value = 8
		self.masks.ghm.value = 8
		self.masks.stoneface.value = 8
		self.masks.wayfarer.value = 8
		
		self.masks.fab_mega_grin.value = 9
		self.masks.fab_mega_doctor.value = 9
		self.masks.fab_mega_alien.value = 9
		self.masks.cop_mega_gage_blade.value = 9
		self.masks.fab_mega_mark.value = 9
		self.masks.dallas_glow.value = 9
		self.masks.wolf_glow.value = 9
		self.masks.hoxton_glow.value = 9
		self.masks.chains_glow.value = 9
			
		self.masks.dgm.global_value = "infamy"
		self.masks.gcm.global_value = "infamy"
		self.masks.gwm.global_value = "infamy"
		self.masks.ghx.global_value = "infamy"
		self.masks.ghm.global_value = "infamy"
		self.masks.stoneface.global_value = "infamy"
		self.masks.wayfarer.global_value = "infamy"
		self.masks.dgm.infamous = true
		self.masks.gcm.infamous = true
		self.masks.gwm.infamous = true
		self.masks.ghx.infamous = true
		self.masks.ghm.infamous = true
		self.masks.stoneface.infamous = true
		self.masks.wayfarer.infamous = true
	end
end
if string.lower(RequiredScript) == "lib/tweak_data/blackmarket/materialstweakdata" then
	local data = BlackMarketTweakData._init_materials
	function BlackMarketTweakData:_init_materials(tweak_data)
		data(self, tweak_data)
		self.materials.bugshell.pcs = {10, 20, 30, 40}
		self.materials.carapace.pcs = {10, 20, 30, 40}
		self.materials.hardshell.pcs = {10, 20, 30, 40}
		self.materials.insectoid.pcs = {10, 20, 30, 40}
		self.materials.carbongrid.pcs = {10, 20, 30, 40}
		self.materials.cosmoline.pcs = {10, 20, 30, 40}
		self.materials.electronic.pcs = {10, 20, 30, 40}
		self.materials.blackmetal.pcs = {10, 20, 30, 40}
		self.materials.gemstone.pcs = {10, 20, 30, 40}
		self.materials.old.pcs = {10, 20, 30, 40}
		self.materials.clay.pcs = {10, 20, 30, 40}
		self.materials.parchment.pcs = {10, 20, 30, 40}
		self.materials.sparks.pcs = {10, 20, 30, 40}
		self.materials.explosive.pcs = {10, 20, 30, 40}
		self.materials.bananapeel.pcs = {10, 20, 30, 40}
		self.materials.leaf.pcs = {10, 20, 30, 40}
		self.materials.bone.pcs = {10, 20, 30, 40}
		self.materials.frost.pcs = {10, 20, 30, 40}
		self.materials.evil.pcs = {10, 20, 30, 40}
		self.materials.void.pcs = {10, 20, 30, 40}
		self.materials.sunset.pcs = {10, 20, 30, 40}
		self.materials.chromescape.pcs = {10, 20, 30, 40}
		self.materials.rubber.pcs = {10, 20, 30, 40}
		self.materials.error.pcs = {10, 20, 30, 40}
		self.materials.rug.pcs = {10, 20, 30, 40}
		self.materials.cushion.pcs = {10, 20, 30, 40}
		self.materials.hatred.pcs = {10, 20, 30, 40}
		self.materials.neon.pcs = {10, 20, 30, 40}
		self.materials.armygreen.pcs = {10, 20, 30, 40}
		self.materials.gunsmoke.pcs = {10, 20, 30, 40}
		self.materials.patriot.pcs = {10, 20, 30, 40}
		self.materials.redsun.pcs = {10, 20, 30, 40}
		self.materials.diamond.pcs = {10, 20, 30, 40}
		self.materials.bandages.pcs = {10, 20, 30, 40}
		self.materials.rust.pcs = {10, 20, 30, 40}
		self.materials.sand.pcs = {10, 20, 30, 40}
		self.materials.meat.pcs = {10, 20, 30, 40}
		self.materials.plywood.pcs = {10, 20, 30, 40}
		self.materials.rhino_skin.pcs = {10, 20, 30, 40}
		self.materials.rock_marble.pcs = {10, 20, 30, 40}
		self.materials.dawn.pcs = {10, 20, 30, 40}
		self.materials.prehistoric.pcs = {10, 20, 30, 40}
		self.materials.fossil.pcs = {10, 20, 30, 40}
		self.materials.feathers.pcs = {10, 20, 30, 40}
		self.materials.candlelight.pcs = {10, 20, 30, 40}
		self.materials.burn.pcs = {10, 20, 30, 40}
		self.materials.toast.pcs = {10, 20, 30, 40}
		self.materials.coal.pcs = {10, 20, 30, 40}
		self.materials.goldfever.pcs = {10, 20, 30, 40}
		self.materials.westernsunset.pcs = {10, 20, 30, 40}
		self.materials.scorpion.pcs = {10, 20, 30, 40}
		self.materials.cactus.pcs = {10, 20, 30, 40}
		self.materials.stained_glass.pcs = {10, 20, 30, 40}
		self.materials.bionic.pcs = {10, 20, 30, 40}
		self.materials.enlightment.pcs = {10, 20, 30, 40}
		self.materials.dimblue.pcs = {10, 20, 30, 40}
		self.materials.carpet.pcs = {10, 20, 30, 40}
		self.materials.casino.pcs = {10, 20, 30, 40}
		self.materials.plush.pcs = {10, 20, 30, 40}
		self.materials.stars.pcs = {10, 20, 30, 40}
		self.materials.still_waters.pcs = {10, 20, 30, 40}
		self.materials.sakura.pcs = {10, 20, 30, 40}
		self.materials.bamboo.pcs = {10, 20, 30, 40}
		self.materials.origami.pcs = {10, 20, 30, 40}
		self.materials.forged.pcs = {10, 20, 30, 40}
		self.materials.blooded.pcs = {10, 20, 30, 40}
		self.materials.chain_armor.pcs = {10, 20, 30, 40}
		self.materials.scale_armor.pcs = {10, 20, 30, 40}
		self.materials.flow.pcs = {10, 20, 30, 40}
		self.materials.sancti.pcs = {10, 20, 30, 40}
		self.materials.glade.pcs = {10, 20, 30, 40}
		self.materials.wade.pcs = {10, 20, 30, 40}
		self.materials.goateye.pcs = {10, 20, 30, 40}
		self.materials.flamingoeye.pcs = {10, 20, 30, 40}
		self.materials.hay.pcs = {10, 20, 30, 40}
		self.materials.tongue.pcs = {10, 20, 30, 40}
		self.materials.day.pcs = {10, 20, 30, 40}
		self.materials.houndstooth.pcs = {10, 20, 30, 40}
		self.materials.redwhite.pcs = {10, 20, 30, 40}
		self.materials.mushroom_cloud.pcs = {10, 20, 30, 40}
		self.materials.nebula.pcs = {10, 20, 30, 40}
		self.materials.planet.pcs = {10, 20, 30, 40}
		self.materials.rusty.pcs = {10, 20, 30, 40}
		self.materials.spaceship.pcs = {10, 20, 30, 40}
		self.materials.chromey.pcs = {10, 20, 30, 40}
		self.materials.devil_eye.pcs = {10, 20, 30, 40}
		self.materials.hotrod_red.pcs = {10, 20, 30, 40}
		self.materials.shiny_and_chrome.pcs = {10, 20, 30, 40}
		self.materials.club.pcs = {10, 20, 30, 40}
		self.materials.mist.pcs = {10, 20, 30, 40}
		self.materials.dog.pcs = {10, 20, 30, 40}
		self.materials.wheel.pcs = {10, 20, 30, 40}
		self.materials.oxidized_copper.pcs = {10, 20, 30, 40}
		self.materials.golden_hour.pcs = {10, 20, 30, 40}
		self.materials.red_velvet.pcs = {10, 20, 30, 40}
		self.materials.black_marble.pcs = {10, 20, 30, 40}
		self.materials.carbon_fiber_weave.pcs = {10, 20, 30, 40}
		self.materials.black_suede.pcs = {10, 20, 30, 40}
		self.materials.neon_blue.pcs = {10, 20, 30, 40}
		self.materials.underground_neon.pcs = {10, 20, 30, 40}
		self.materials.russian_camouflage.pcs = {10, 20, 30, 40}
		self.materials.ceramics_gzhel.pcs = {10, 20, 30, 40}
		self.materials.propaganda_palette.pcs = {10, 20, 30, 40}
		self.materials.tricolor.pcs = {10, 20, 30, 40}
		
		self.materials.bugshell.value = 4
		self.materials.carapace.value = 4
		self.materials.hardshell.value = 4
		self.materials.insectoid.value = 4
		self.materials.carbongrid.value = 5
		self.materials.cosmoline.value = 5
		self.materials.electronic.value = 5
		self.materials.blackmetal.value = 5
		self.materials.gemstone.value = 5
		self.materials.old.value = 5
		self.materials.clay.value = 5
		self.materials.parchment.value = 5
		self.materials.sparks.value = 4
		self.materials.explosive.value = 4
		self.materials.bananapeel.value = 4
		self.materials.leaf.value = 4
		self.materials.bone.value = 5
		self.materials.frost.value = 5
		self.materials.evil.value = 5
		self.materials.void.value = 5
		self.materials.sunset.value = 4
		self.materials.chromescape.value = 4
		self.materials.rubber.value = 4
		self.materials.error.value = 4
		self.materials.rug.value = 4
		self.materials.cushion.value = 4
		self.materials.hatred.value = 4
		self.materials.neon.value = 4
		self.materials.armygreen.value = 4
		self.materials.gunsmoke.value = 4
		self.materials.patriot.value = 4
		self.materials.redsun.value = 4
		self.materials.diamond.value = 6
		self.materials.bandages.value = 6
		self.materials.rust.value = 6
		self.materials.sand.value = 6
		self.materials.meat.value = 5
		self.materials.plywood.value = 5
		self.materials.rhino_skin.value = 5
		self.materials.rock_marble.value = 5
		self.materials.dawn.value = 5
		self.materials.prehistoric.value = 5
		self.materials.fossil.value = 5
		self.materials.feathers.value = 5
		self.materials.candlelight.value = 5
		self.materials.burn.value = 5
		self.materials.toast.value = 5
		self.materials.coal.value = 5
		self.materials.goldfever.value = 5
		self.materials.westernsunset.value = 5
		self.materials.scorpion.value = 5
		self.materials.cactus.value = 5
		self.materials.stained_glass.value = 5
		self.materials.bionic.value = 5
		self.materials.enlightment.value = 5
		self.materials.dimblue.value = 5
		self.materials.carpet.value = 5
		self.materials.casino.value = 5
		self.materials.plush.value = 5
		self.materials.stars.value = 5
		self.materials.still_waters.value = 5
		self.materials.sakura.value = 5
		self.materials.bamboo.value = 5
		self.materials.origami.value = 5
		self.materials.forged.value = 5
		self.materials.blooded.value = 5
		self.materials.chain_armor.value = 5
		self.materials.scale_armor.value = 5
		self.materials.flow.value = 5
		self.materials.sancti.value = 5
		self.materials.glade.value = 5
		self.materials.wade.value = 5
		self.materials.goateye.value = 5
		self.materials.flamingoeye.value = 5
		self.materials.hay.value = 5
		self.materials.tongue.value = 5
		self.materials.day.value = 5
		self.materials.houndstooth.value = 5
		self.materials.redwhite.value = 5
		self.materials.mushroom_cloud.value = 5
		self.materials.nebula.value = 5
		self.materials.planet.value = 5
		self.materials.rusty.value = 5
		self.materials.spaceship.value = 5
		self.materials.chromey.value = 5
		self.materials.devil_eye.value = 5
		self.materials.hotrod_red.value = 5
		self.materials.shiny_and_chrome.value = 5
		self.materials.club.value = 5
		self.materials.mist.value = 5
		self.materials.dog.value = 5
		self.materials.wheel.value = 5
		self.materials.oxidized_copper.value = 5
		self.materials.golden_hour.value = 5
		self.materials.red_velvet.value = 5
		self.materials.black_marble.value = 5
		self.materials.carbon_fiber_weave.value = 5
		self.materials.black_suede.value = 5
		self.materials.neon_blue.value = 5
		self.materials.underground_neon.value = 5
		self.materials.russian_camouflage.value = 5
		self.materials.ceramics_gzhel.value = 5
		self.materials.propaganda_palette.value = 5
		self.materials.tricolor.value = 5
		
	end
end
if string.lower(RequiredScript) == "lib/tweak_data/blackmarket/texturestweakdata" then
	local data = BlackMarketTweakData._init_textures
	function BlackMarketTweakData:_init_textures(tweak_data)
		data(self, tweak_data)
		
		self.textures.agatha.pcs = {10, 20, 30, 40}
		self.textures.arena_logo.pcs = {10, 20, 30, 40}
		self.textures.baba_yaga.pcs = {10, 20, 30, 40}
		self.textures.banana.pcs = {10, 20, 30, 40}
		self.textures.bear_fight.pcs = {10, 20, 30, 40}
		self.textures.biker_face.pcs = {10, 20, 30, 40}
		self.textures.bsomebody.pcs = {10, 20, 30, 40}
		self.textures.bugger.pcs = {10, 20, 30, 40}
		self.textures.captainwar.pcs = {10, 20, 30, 40}
		self.textures.cards.pcs = {10, 20, 30, 40}
		self.textures.checkered_out.pcs = {10, 20, 30, 40}
		self.textures.chief.pcs = {10, 20, 30, 40}
		self.textures.chips.pcs = {10, 20, 30, 40}
		self.textures.circle_raster.pcs = {10, 20, 30, 40}
		self.textures.continental.pcs = {10, 20, 30, 40}
		self.textures.coyote.pcs = {10, 20, 30, 40}
		self.textures.cro_pattern_1.pcs = {10, 20, 30, 40}
		self.textures.cro_pattern_2.pcs = {10, 20, 30, 40}
		self.textures.cro_pattern_3.pcs = {10, 20, 30, 40}
		self.textures.cro_pattern_4.pcs = {10, 20, 30, 40}
		self.textures.daisy.pcs = {10, 20, 30, 40}
		self.textures.dazzle.pcs = {10, 20, 30, 40}
		self.textures.death.pcs = {10, 20, 30, 40}
		self.textures.deathcube.pcs = {10, 20, 30, 40}
		self.textures.deathdealer.pcs = {10, 20, 30, 40}
		self.textures.diablada.pcs = {10, 20, 30, 40}
		self.textures.dices.pcs = {10, 20, 30, 40}
		self.textures.dinoscars.pcs = {10, 20, 30, 40}
		self.textures.dinoskull.pcs = {10, 20, 30, 40}
		self.textures.dinostripes.pcs = {10, 20, 30, 40}
		self.textures.doodles.pcs = {10, 20, 30, 40}
		self.textures.emperor.pcs = {10, 20, 30, 40}
		self.textures.fenris.pcs = {10, 20, 30, 40}
		self.textures.filthythirteen.pcs = {10, 20, 30, 40}
		self.textures.fireborn.pcs = {10, 20, 30, 40}
		self.textures.flamer.pcs = {10, 20, 30, 40}
		self.textures.flammable.pcs = {10, 20, 30, 40}
		self.textures.fur.pcs = {10, 20, 30, 40}
		self.textures.giraffe.pcs = {10, 20, 30, 40}
		self.textures.goatface.pcs = {10, 20, 30, 40}
		self.textures.hawkhelm.pcs = {10, 20, 30, 40}
		self.textures.hexagons.pcs = {10, 20, 30, 40}
		self.textures.hieroglyphs.pcs = {10, 20, 30, 40}
		self.textures.hiptobepolygon.pcs = {10, 20, 30, 40}
		self.textures.hood_stripes.pcs = {10, 20, 30, 40}
		self.textures.horus.pcs = {10, 20, 30, 40}
		self.textures.hotel_pattern.pcs = {10, 20, 30, 40}
		self.textures.hotflames.pcs = {10, 20, 30, 40}
		self.textures.hotline.pcs = {10, 20, 30, 40}
		self.textures.illumigoati.pcs = {10, 20, 30, 40}
		self.textures.jimmy_phoenix.pcs = {10, 20, 30, 40}
		self.textures.koi.pcs = {10, 20, 30, 40}
		self.textures.kraken.pcs = {10, 20, 30, 40}
		self.textures.kurbits.pcs = {10, 20, 30, 40}
		self.textures.leopard.pcs = {10, 20, 30, 40}
		self.textures.liberty_flame.pcs = {10, 20, 30, 40}
		self.textures.luse.pcs = {10, 20, 30, 40}
		self.textures.mason.pcs = {10, 20, 30, 40}
		self.textures.med_pat.pcs = {10, 20, 30, 40}
		self.textures.monkeyskull.pcs = {10, 20, 30, 40}
		self.textures.muerte.pcs = {10, 20, 30, 40}
		self.textures.my_little.pcs = {10, 20, 30, 40}
		self.textures.native.pcs = {10, 20, 30, 40}
		self.textures.oneshot.pcs = {10, 20, 30, 40}
		self.textures.oni.pcs = {10, 20, 30, 40}
		self.textures.origami.pcs = {10, 20, 30, 40}
		self.textures.ornamentalcrown.pcs = {10, 20, 30, 40}
		self.textures.palmtrees.pcs = {10, 20, 30, 40}
		self.textures.pattern.pcs = {10, 20, 30, 40}
		self.textures.piety.pcs = {10, 20, 30, 40}
		self.textures.pizzaface.pcs = {10, 20, 30, 40}
		self.textures.predator.pcs = {10, 20, 30, 40}
		self.textures.prison_statement.pcs = {10, 20, 30, 40}
		self.textures.rebel.pcs = {10, 20, 30, 40}
		self.textures.red_star.pcs = {10, 20, 30, 40}
		self.textures.roman.pcs = {10, 20, 30, 40}
		self.textures.royale.pcs = {10, 20, 30, 40}
		self.textures.ruler.pcs = {10, 20, 30, 40}
		self.textures.runes.pcs = {10, 20, 30, 40}
		self.textures.russian_gamble.pcs = {10, 20, 30, 40}
		self.textures.scar_mask.pcs = {10, 20, 30, 40}
		self.textures.shutupandbleed.pcs = {10, 20, 30, 40}
		self.textures.skull_engine.pcs = {10, 20, 30, 40}
		self.textures.skull_wing.pcs = {10, 20, 30, 40}
		self.textures.smoke.pcs = {10, 20, 30, 40}
		self.textures.soundwave.pcs = {10, 20, 30, 40}
		self.textures.spartan.pcs = {10, 20, 30, 40}
		self.textures.spidereyes.pcs = {10, 20, 30, 40}
		self.textures.split.pcs = {10, 20, 30, 40}
		self.textures.squares.pcs = {10, 20, 30, 40}
		self.textures.starvr.pcs = {10, 20, 30, 40}
		self.textures.sunavatar.pcs = {10, 20, 30, 40}
		self.textures.tcn.pcs = {10, 20, 30, 40}
		self.textures.terror.pcs = {10, 20, 30, 40}
		self.textures.tire_fire.pcs = {10, 20, 30, 40}
		self.textures.totem.pcs = {10, 20, 30, 40}
		self.textures.tribalface.pcs = {10, 20, 30, 40}
		self.textures.tribalstroke.pcs = {10, 20, 30, 40}
		self.textures.tribalwave.pcs = {10, 20, 30, 40}
		self.textures.uglyrug.pcs = {10, 20, 30, 40}
		self.textures.venomous.pcs = {10, 20, 30, 40}
		self.textures.vicious.pcs = {10, 20, 30, 40}
		self.textures.warface.pcs = {10, 20, 30, 40}
		self.textures.wargod.pcs = {10, 20, 30, 40}
		self.textures.wingsofdeath.pcs = {10, 20, 30, 40}
		self.textures.youkai.pcs = {10, 20, 30, 40}

		self.textures.agatha.value = 5
		self.textures.arena_logo.value = 5
		self.textures.baba_yaga.value = 5
		self.textures.banana.value = 5
		self.textures.bear_fight.value = 5
		self.textures.biker_face.value = 5
		self.textures.bsomebody.value = 5
		self.textures.bugger.value = 5
		self.textures.captainwar.value = 5
		self.textures.cards.value = 5
		self.textures.checkered_out.value = 5
		self.textures.chief.value = 5
		self.textures.chips.value = 5
		self.textures.circle_raster.value = 5
		self.textures.continental.value = 5
		self.textures.coyote.value = 5
		self.textures.cro_pattern_1.value = 5
		self.textures.cro_pattern_2.value = 5
		self.textures.cro_pattern_3.value = 5
		self.textures.cro_pattern_4.value = 5
		self.textures.daisy.value = 5
		self.textures.dazzle.value = 5
		self.textures.death.value = 5
		self.textures.deathcube.value = 5
		self.textures.deathdealer.value = 5
		self.textures.diablada.value = 5
		self.textures.dices.value = 5
		self.textures.dinoscars.value = 5
		self.textures.dinoskull.value = 5
		self.textures.dinostripes.value = 5
		self.textures.doodles.value = 5
		self.textures.emperor.value = 5
		self.textures.fenris.value = 5
		self.textures.filthythirteen.value = 5
		self.textures.fireborn.value = 5
		self.textures.flamer.value = 5
		self.textures.flammable.value = 5
		self.textures.fur.value = 5
		self.textures.giraffe.value = 5
		self.textures.goatface.value = 5
		self.textures.hawkhelm.value = 5
		self.textures.hexagons.value = 5
		self.textures.hieroglyphs.value = 5
		self.textures.hiptobepolygon.value = 5
		self.textures.hood_stripes.value = 5
		self.textures.horus.value = 5
		self.textures.hotel_pattern.value = 5
		self.textures.hotflames.value = 5
		self.textures.hotline.value = 5
		self.textures.illumigoati.value = 5
		self.textures.jimmy_phoenix.value = 5
		self.textures.koi.value = 5
		self.textures.kraken.value = 5
		self.textures.kurbits.value = 5
		self.textures.leopard.value = 5
		self.textures.liberty_flame.value = 5
		self.textures.luse.value = 5
		self.textures.mason.value = 5
		self.textures.med_pat.value = 5
		self.textures.monkeyskull.value = 5
		self.textures.muerte.value = 5
		self.textures.my_little.value = 5
		self.textures.native.value = 5
		self.textures.oneshot.value = 5
		self.textures.oni.value = 5
		self.textures.origami.value = 5
		self.textures.ornamentalcrown.value = 5
		self.textures.palmtrees.value = 5
		self.textures.pattern.value = 5
		self.textures.piety.value = 5
		self.textures.pizzaface.value = 5
		self.textures.predator.value = 5
		self.textures.prison_statement.value = 5
		self.textures.rebel.value = 5
		self.textures.red_star.value = 5
		self.textures.roman.value = 5
		self.textures.royale.value = 5
		self.textures.ruler.value = 5
		self.textures.runes.value = 5
		self.textures.russian_gamble.value = 5
		self.textures.scar_mask.value = 5
		self.textures.shutupandbleed.value = 5
		self.textures.skull_engine.value = 5
		self.textures.skull_wing.value = 5
		self.textures.smoke.value = 5
		self.textures.soundwave.value = 5
		self.textures.spartan.value = 5
		self.textures.spidereyes.value = 5
		self.textures.split.value = 5
		self.textures.squares.value = 5
		self.textures.starvr.value = 5
		self.textures.sunavatar.value = 5
		self.textures.tcn.value = 5
		self.textures.terror.value = 5
		self.textures.tire_fire.value = 5
		self.textures.totem.value = 5
		self.textures.tribalface.value = 5
		self.textures.tribalstroke.value = 5
		self.textures.tribalwave.value = 5
		self.textures.uglyrug.value = 5
		self.textures.venomous.value = 5
		self.textures.vicious.value = 5
		self.textures.warface.value = 5
		self.textures.wargod.value = 5
		self.textures.wingsofdeath.value = 5
		self.textures.youkai.value = 5
	end
end