function TipsTweakData:init()
	self.tips = {
		{cat_index = 1,		image = "crimenet_heists",			consoles = true, category = "op_gameplay"},
		{cat_index = 2,		image = "enemy_flashbang",			consoles = true, category = "op_gameplay"},
		{cat_index = 3,		image = "enemy_medic",				consoles = true, category = "op_gameplay"},
		{cat_index = 4,		image = "enemy_guards",				consoles = true, category = "op_gameplay"},
		{cat_index = 5,		image = "general_pagers",			consoles = true, category = "op_gameplay"},
		{cat_index = 6,		image = "general_pagers",			consoles = true, category = "op_gameplay"},
		{cat_index = 7,		image = "tactics_stealth",			consoles = true, category = "op_gameplay"},
		{cat_index = 8,		image = "tactics_ghost",			consoles = true, category = "op_gameplay"},
		{cat_index = 9,		image = "general_hostages",			consoles = true, category = "op_gameplay"},
		{cat_index = 10,	image = "enemy_guards",				consoles = true, category = "op_gameplay"},
		{cat_index = 11,	image = "weapon_tripmine",			consoles = true, category = "op_gameplay"},
		{cat_index = 12,	image = "crimenet_heists",			consoles = true, category = "op_gameplay"},
		{cat_index = 13,	image = "general_drill",			consoles = true, category = "op_gameplay"},
		{cat_index = 14,	image = "tactics_casingmode",		consoles = true, category = "op_gameplay"},
		{cat_index = 15,	image = "tactics_bagweight",		consoles = true, category = "op_gameplay"},
		{cat_index = 16,	image = "general_cameras",			consoles = true, category = "op_gameplay"},
		{cat_index = 17,	image = "tactics_revive",			consoles = true, category = "op_gameplay"},
		{cat_index = 18,	image = "tactics_cover",			consoles = true, category = "op_gameplay"},
		{cat_index = 19,	image = "general_perks",			consoles = true, category = "op_gameplay"},
		{cat_index = 20,	image = "general_wanted_poster",	consoles = true, category = "op_gameplay"},
		{cat_index = 21,	image = "crimenet_difficulty",		consoles = true, category = "op_gameplay"},
		{cat_index = 22,	image = "general_achievements",		consoles = true, category = "op_gameplay"},
		{cat_index = 23,	image = "crimenet_safehouse",		consoles = true, category = "op_gameplay"},
		{cat_index = 24,	image = "weapon_sniper",			consoles = true, category = "op_gameplay"},
		{cat_index = 25,	image = "enemy_zeal",				consoles = true, category = "op_gameplay"},
		{cat_index = 26,	image = "tactics_stealth",			consoles = true, category = "op_gameplay"},
		{cat_index = 27,	image = "heist_events",				consoles = true, category = "op_gameplay"},
		{cat_index = 28,	image = "equipment_ammobag",		consoles = true, category = "op_gameplay"},
		{cat_index = 29,	image = "weapon_explosives",		consoles = true, category = "op_gameplay"},
		{cat_index = 30,	image = "general_escapes",			consoles = true, category = "op_gameplay"},
		{cat_index = 31,	image = "general_hostages",			consoles = true, category = "op_gameplay"},
		{cat_index = 32,	image = "general_cleanercosts",		consoles = true, category = "op_gameplay"},
		{cat_index = 33,	image = "weapon_gadgets",			consoles = true, category = "op_gameplay"},
		{cat_index = 34,	image = "general_difficulty",		consoles = true, category = "op_gameplay"},
		{cat_index = 35,	image = "crimenet_fbifiles",		consoles = true, category = "op_gameplay"},
		{cat_index = 36,	image = "crimenet_heists",			consoles = true, category = "op_gameplay"},
		{cat_index = 37,	image = "general_enforcer",			consoles = true, category = "op_gameplay"},
		{cat_index = 38,	image = "tactics_stealth",			consoles = true, category = "op_gameplay"},
		{cat_index = 39,	image = "general_civilians",		consoles = true, category = "op_gameplay"},
		{cat_index = 40,	image = "contact_classics",			consoles = true, category = "op_gameplay"},
		{cat_index = 41,	image = "general_cameras",			consoles = true, category = "op_gameplay"},
		{cat_index = 42,	image = "tactics_shooting",			consoles = true, category = "op_gameplay"},
		{cat_index = 43,	image = "general_difficulty",		consoles = true, category = "op_gameplay"},
		{cat_index = 44,	image = "tactics_headshot",			consoles = true, category = "op_gameplay"},
		{cat_index = 45,	image = "crimenet_difficulty",		consoles = true, category = "op_gameplay"},
		{cat_index = 46,	image = "enemy_cloaker",			consoles = true, category = "op_gameplay"},
		{cat_index = 47,	image = "enemy_flashbang",			consoles = true, category = "op_gameplay"},
		{cat_index = 48,	image = "general_wanted_poster",	consoles = true, category = "op_gameplay"},
		{cat_index = 49,	image = "general_loadout",			consoles = true, category = "op_gameplay"},
		{cat_index = 50,	image = "tactics_stealth",			consoles = true, category = "op_gameplay"},
		{cat_index = 51,	image = "tactics_marking_enemies",	consoles = true, category = "op_gameplay"},
		{cat_index = 52,	image = "general_technician",		consoles = true, category = "op_gameplay"},
		{cat_index = 53,	image = "general_drill",			consoles = true, category = "op_gameplay"},
		{cat_index = 54,	image = "general_mastermind",		consoles = true, category = "op_gameplay"},
		{cat_index = 55,	image = "general_interaction",		consoles = true, category = "op_gameplay"},
		{cat_index = 56,	image = "enemy_turret",				consoles = true, category = "op_gameplay"},
		{cat_index = 57,	image = "tactics_ecm",				consoles = true, category = "op_gameplay"},
		{cat_index = 58,	image = "general_fugitive",			consoles = true, category = "op_gameplay"},
		{cat_index = 59,	image = "general_ghost",			consoles = true, category = "op_gameplay"},
		{cat_index = 60,	image = "general_skills",			consoles = true, category = "op_gameplay"},
		{cat_index = 61,	image = "general_gage",				consoles = true, category = "op_gameplay"},
		{cat_index = 62,	image = "tactics_cover",			consoles = true, category = "op_gameplay"},
		{cat_index = 63,	image = "tactics_objectives",		consoles = true, category = "op_gameplay"},
		{cat_index = 64,	image = "general_loot",				consoles = true, category = "op_gameplay"},
		{cat_index = 65,	image = "weapon_primary_secondary",	consoles = true, category = "op_gameplay"},
		{cat_index = 66,	image = "tactics_cover",			consoles = true, category = "op_gameplay"},
		{cat_index = 67,	image = "weapon_explosives",		consoles = true, category = "op_gameplay"},
		{cat_index = 68,	image = "general_heisters",			consoles = true, category = "op_gameplay"},
		{cat_index = 69,	image = "general_preplanning",		consoles = true, category = "op_gameplay"},
		{cat_index = 70,	image = "tactics_helping_up",		consoles = true, category = "op_gameplay"},
		{cat_index = 71,	image = "tactics_ecm",				consoles = true, category = "op_gameplay"},
		{cat_index = 72,	image = "tactics_stealth",			consoles = true, category = "op_gameplay"},
		{cat_index = 73,	image = "general_equipment",		consoles = true, category = "op_gameplay"},
		{cat_index = 74,	image = "general_difficulty",		consoles = true, category = "op_gameplay"},
		{cat_index = 75,	image = "enemy_gensec",				consoles = true, category = "op_gameplay"},
		{cat_index = 76,	image = "general_equipment",		consoles = true, category = "op_gameplay"},
		{cat_index = 77,	image = "tactics_casingmode",		consoles = true, category = "op_gameplay"},
		{cat_index = 78,	image = "general_equipment",		consoles = true, category = "op_gameplay"},
		{cat_index = 1,		image = "general_jules",			consoles = true, category = "op_trivia"}
	}
	self.category_totals = {}

	for _, tip in ipairs(self.tips) do
		if not self.category_totals[tip.category] or self.category_totals[tip.category] < tip.cat_index then
			self.category_totals[tip.category] = tip.cat_index
		end
	end
end